"""sex column changed

Revision ID: 2c4105dd3876
Revises: 06a7d296ef99
Create Date: 2025-08-20 08:28:47.910198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c4105dd3876'
down_revision = '06a7d296ef99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=mysql.VARCHAR(length=1),
               type_=sa.String(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=sa.String(length=6),
               type_=mysql.VARCHAR(length=1),
               existing_nullable=False)

    # ### end Alembic commands ###
