"""change on models.py

Revision ID: 06a7d296ef99
Revises: e2ca045e601c
Create Date: 2025-08-20 08:25:18.891916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06a7d296ef99'
down_revision = 'e2ca045e601c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_employee')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)
        batch_op.drop_column('surname')

    op.create_table('admin_employee',
    sa.Column('admin_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('admin_employee_ibfk_1')),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('admin_employee_ibfk_2')),
    sa.PrimaryKeyConstraint('admin_id', 'employee_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
